server:
  context-path: /seller
  port: 8099

rpc.manager.url: http://localhost:8999/manager

logging:
  level:
    com.googlecode.jsonrpc4j: debug

spring:
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://192.168.241.128:61616
    packages:
      trust-all: true     # 所有包下面的对象都可作为事件对象