server:
  servlet:
    context-path: /seller
  port: 8099

rpc.manager.url: http://localhost:8999/manager

logging:
  level:
    com.googlecode.jsonrpc4j: debug

spring:
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://192.168.241.128:61616
    packages:
      trust-all: true     # 所有包下面的对象都可作为事件对象
  datasource:
    url: jdbc:mysql://localhost:3306/seller?user=root&password=&userUnicode=true&characterEncoding=UTF-8
    jpa:
      show-sql: true    # 打印sql语句

swagger:
  groupName: seller
  basePackage: com.glw.seller.controller