spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=&userUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true    # 打印sql语句
  activemq:
    broker-url: tcp://192.168.241.128:61616
  jms:
    pub-sub-domain: true    # 发布订阅消息

server:
  servlet:
    context-path: /manager
  port: 8999

swagger:
  groupName: manager
  basePackage: com.glw.manager.controller

logging:
  level:
    com.googlecode.jsonrpc4j: debug